# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
${custom.giturl}\
$git_branch\
${custom.git_branch}\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$aws\
$gcloud\
$openstack\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3000

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](bold red) '

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = 'get_git_host'                                  # ~/.local/bin
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "214"
format = "at [$output]($style) "

[docker_context]
format = 'in [🐋 ](blue bold)'

[git_status]
disabled = true

[git_branch]
disabled = true

[custom.git_branch]
description = "Customized git branch"
command = 'get_git_branch'                                # ~/.local/bin
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = 'bold purple'
symbol = ' '
format = 'on [$symbol$output]($style) '

[gcloud]
# format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
format = 'on [$symbol ($project)]($style) '
symbol = '️󱇶'
[gcloud.project_aliases]
rapidprototypingenv-112647 = 'rp'
